---
galaxy_info:
  author: sapr797
  description: Роль для управления файлами в Yandex Cloud
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
  galaxy_tags:
    - yandex
    - cloud
    - file
dependencies: []
